const Images = {
  //Images
  // : require(''),
  rightTickSuccessIcon: require('./rightTickSuccessIcon.png'),
  sendBtn: require('./sendBtn.png'),
  frontBackCamera: require('./frontBackCamera.png'),
  settings: require('./settings.png'),
  audioOff: require('./audioOff.png'),
  start: require('./start.png'),
  stop: require('./stop.png'),
  audioOn: require('./audioOn.png'),

  redExclamation: require('./redExclamation.png'),

  // seller
  backgroundImg: require('./backgroundImg.png'),
  whiteBackground: require('./whiteBackground.png'),
  logo: require('./logo.png'),
  passwordLock: require('./passwordLock.png'),
  passwordView: require('./passwordView.png'),
  userIcon: require('./userIcon.png'),
  lock: require('./lock.png'),

  //buyer
  buyerPlayIcon: require('./buyerPlayIcon.png'),
  buyerPauseIcon: require('./buyerPauseIcon.png'),
  waveHand: require('./waveHand.png'),
  mute: require('./mute.png'),
  share: require('./share.png'),
  pay: require('./pay.png'),
  brod: require('./brod.png'),
  mute_on: require('./mute_on.png'),
  soundWave: require('./soundWave.png'),
  star: require('./star.png'),
  downArrow: require('./downArrow.png'),
  visa: require('./visa.jpeg'),

  email: require('./email.png'),
  search: require('./search.png'),
  grid: require('./grid.png'),

  play: require('./play.png'),
  notifications: require('./notifications.png'),
  setting: require('./setting.png'),
  logout: require('./logout.png'),
  checkbox: require('./checkbox.png'),
  checkboxChecked: require('./checkboxChecked.png'),
  mobile: require('./mobile.png'),
  affilicationcode: require('./affilicationcode.png'),
  backIcon: require('./backIcon.png'),
  changePasswordImage: require('./changePasswordImage.png'),
  paymentImage: require('./paymentImage.png'),
  profileImage: require('./profileImage.png'),
  editImages: require('./editImages.png'),
  rightArrowIcon: require('./rightArrowIcon.png'),
  otpImages: require('./otp.png'),
  menuImage: require('./menuImage.png'),
  homeImage: require('./homeImage.png'),
  upArrowImage: require('./upArrowImage.png'),
  paymentcard: require('./paymentcard.png'),
  icondown: require('./icondown.png'),
  home: require('./home.png'),
};
export default c;
